# Generated by Django 6.0.3 on 2026-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='componentName',
            field=models.CharField(choices=[('bp', 'Blood Pressure'), ('hw', 'Height/Weight'), ('heartrate', 'Heart Rate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='measuredDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
