# Generated by Django 6.0.3 on 2026-05-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
