# Generated by Django 6.0.3 on 2026-04-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormApp', '0006_order_price_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
